import type { AnyLocatorKind, Candidate, LocatorKind, Section, Stability } from './types';

const KIND_BASE: Record<AnyLocatorKind, { stability: Stability; section: Section }> = {
  testid: { stability: 'best', section: 'recommended' },
  id: { stability: 'best', section: 'recommended' },
  role: { stability: 'best', section: 'recommended' },
  label: { stability: 'good', section: 'alternative' },
  placeholder: { stability: 'good', section: 'alternative' },
  altText: { stability: 'good', section: 'alternative' },
  text: { stability: 'good', section: 'alternative' },
  title: { stability: 'ok', section: 'alternative' },
  name: { stability: 'good', section: 'alternative' },
  chained: { stability: 'good', section: 'alternative' },
  css: { stability: 'ok', section: 'fallback' },
  xpath: { stability: 'ok', section: 'fallback' },
  xpathAbs: { stability: 'fragile', section: 'fallback' },
  xpathPos: { stability: 'fragile', section: 'fallback' },
  'smart-placeholder': { stability: 'good', section: 'smart' },
  'smart-name': { stability: 'good', section: 'smart' },
  'smart-id': { stability: 'best', section: 'smart' },
  'smart-label': { stability: 'good', section: 'smart' },
  'axis-ancestor': { stability: 'ok', section: 'axes' },
  'axis-following': { stability: 'ok', section: 'axes' },
  'axis-preceding': { stability: 'ok', section: 'axes' },
  'axis-followingSibling': { stability: 'ok', section: 'axes' },
  'axis-precedingSibling': { stability: 'ok', section: 'axes' },
  'axis-parent': { stability: 'ok', section: 'axes' },
  'rel-above': { stability: 'ok', section: 'relative' },
  'rel-below': { stability: 'ok', section: 'relative' },
  'rel-near': { stability: 'ok', section: 'relative' },
  'rel-toLeftOf': { stability: 'ok', section: 'relative' },
  'rel-toRightOf': { stability: 'ok', section: 'relative' },
};

export function classify(kind: AnyLocatorKind): { stability: Stability; section: Section } {
  return KIND_BASE[kind];
}

export function adjustForUniqueness(c: Candidate): Candidate {
  if (c.matchCount === 0) return { ...c, stability: 'fragile' };
  if (!c.isUnique && c.section === 'recommended') {
    return { ...c, stability: c.matchCount <= 3 ? 'ok' : 'fragile', section: 'alternative' };
  }
  return c;
}

export const STABILITY_ORDER: Record<Stability, number> = { best: 0, good: 1, ok: 2, fragile: 3 };
export const SECTION_ORDER: Record<Section, number> = { recommended: 0, smart: 1, alternative: 2, axes: 3, relative: 4, fallback: 5 };

export const STABILITY_STARS: Record<Stability, string> = {
  best: '●●●',
  good: '●●○',
  ok: '●○○',
  fragile: '○○○',
};

export const STABILITY_LABEL: Record<Stability, string> = {
  best: 'best',
  good: 'good',
  ok: 'ok',
  fragile: 'fragile',
};

export const SECTION_TITLE: Record<Section, string> = {
  recommended: 'Recommended',
  smart: 'Smart Patterns',
  alternative: 'Alternative',
  axes: 'XPath Axes',
  relative: 'Selenium 4 Relative',
  fallback: 'Fallback',
};

export const SECTION_HINT: Record<Section, string> = {
  recommended: 'Stable, semantic, unique',
  smart: 'Parameterized templates for inputs',
  alternative: 'Works but less robust',
  axes: 'Relative xpath (ancestor / following / sibling)',
  relative: 'Locator relative to nearby anchor (Selenium 4+)',
  fallback: 'Brittle — use only when nothing else fits',
};

export const RATIONALE: Record<Stability, string> = {
  best: 'Highly stable — built for automation or backed by semantic guarantees.',
  good: 'Reasonably stable — depends on copy or attribute review during refactors.',
  ok: 'Workable — structural or proximity-based, sensitive to layout/DOM changes.',
  fragile: 'Brittle — index or absolute path, breaks on minor edits.',
};

const KIND_RATIONALE: Partial<Record<AnyLocatorKind, Partial<Record<Stability, string>>>> = {
  testid: {
    best: 'Custom test attribute — meant for automation, immune to UI changes.',
    good: 'Custom test attribute — usually stable, watch for duplicates.',
    ok: 'Custom test attribute — duplicated on this page, consider scoping.',
    fragile: 'Custom test attribute — too many matches to be reliable here.',
  },
  id: {
    best: 'Unique id — fastest selector when stable.',
    good: 'id attribute — stable but verify it is not autogenerated.',
    ok: 'id attribute — not unique on this page, consider chaining.',
    fragile: 'id attribute — duplicated or autogenerated, unreliable.',
  },
  role: {
    best: 'Semantic ARIA role — works across redesigns, accessible by default.',
    good: 'ARIA role — solid choice, verify accessible name distinguishes siblings.',
    ok: 'ARIA role — multiple matches, add a name or scope.',
    fragile: 'ARIA role — too generic to identify this element.',
  },
  name: {
    best: 'name attribute — stable for form fields with backend contracts.',
    good: 'name attribute — typically stable when form is backed by a server contract.',
    ok: 'name attribute — multiple matches on this page.',
    fragile: 'name attribute — duplicated or generic.',
  },
  label: {
    best: 'Form label text — paired with input via for/id, very robust.',
    good: 'Form label text — stable when copy is reviewed.',
    ok: 'Form label text — copy can change with translations or redesigns.',
    fragile: 'Form label text — likely matches multiple inputs.',
  },
  placeholder: {
    best: 'Placeholder text — stable when designs are mature.',
    good: 'Placeholder text — breaks if copy is reworded.',
    ok: 'Placeholder text — generic, may match many fields.',
    fragile: 'Placeholder text — too generic or absent.',
  },
  altText: {
    best: 'Image alt text — stable when accessibility is reviewed.',
    good: 'Image alt text — depends on a11y review of source copy.',
    ok: 'Image alt text — generic phrase, may collide.',
    fragile: 'Image alt text — missing or too generic.',
  },
  title: {
    best: 'title attribute — stable when used intentionally.',
    good: 'title attribute — stable but secondary to role/label.',
    ok: 'title attribute — often decorative, treat with caution.',
    fragile: 'title attribute — empty or generic.',
  },
  text: {
    best: 'Visible text content — durable for landmark copy.',
    good: 'Visible text content — breaks if copy changes.',
    ok: 'Visible text content — short or generic, may match many nodes.',
    fragile: 'Visible text content — too short or duplicated to scope.',
  },
  chained: {
    best: 'Scoped to a landmark anchor — very low collision risk.',
    good: 'Scoped to ancestor section — limits collisions.',
    ok: 'Scoped path — anchor is generic, still better than raw selectors.',
    fragile: 'Scoped path — anchor itself is not stable.',
  },
  css: {
    best: 'CSS selector — semantic class with no autogen markers.',
    good: 'CSS selector — readable, but check for autogenerated classes.',
    ok: 'CSS selector — depends on class names and tree shape.',
    fragile: 'CSS selector — position-based, breaks when siblings reorder.',
  },
  xpath: {
    best: 'Structural xpath — built around stable attributes.',
    good: 'Structural xpath — workable, prefer role/label when possible.',
    ok: 'Structural xpath — survives minor DOM tweaks, breaks on big refactors.',
    fragile: 'Structural xpath — heavily indexed, breaks on reorder.',
  },
  xpathAbs: {
    best: 'Absolute path — never recommended.',
    good: 'Absolute path — never recommended.',
    ok: 'Absolute path — never recommended.',
    fragile: 'Absolute path from root — breaks on any sibling reorder.',
  },
  xpathPos: {
    best: 'Position-based xpath — never recommended.',
    good: 'Position-based xpath — never recommended.',
    ok: 'Position-based xpath — breaks when siblings reorder.',
    fragile: 'Position-based — breaks when siblings reorder.',
  },
  'smart-placeholder': {
    best: 'Parameterized: pass the placeholder at runtime.',
    good: 'Parameterized: pass the placeholder at runtime.',
    ok: 'Parameterized template — placeholder copy may change.',
    fragile: 'Parameterized template — placeholder is missing or noisy.',
  },
  'smart-name': {
    best: 'Parameterized: pass the name at runtime.',
    good: 'Parameterized: pass the name attribute at runtime.',
    ok: 'Parameterized template — name attribute may collide.',
    fragile: 'Parameterized template — name attribute is generic.',
  },
  'smart-id': {
    best: 'Parameterized: pass the id at runtime.',
    good: 'Parameterized: pass the id at runtime.',
    ok: 'Parameterized template — id may be autogenerated.',
    fragile: 'Parameterized template — id looks autogenerated.',
  },
  'smart-label': {
    best: 'Parameterized: pass the label at runtime.',
    good: 'Parameterized: pass the label at runtime.',
    ok: 'Parameterized template — label copy may change.',
    fragile: 'Parameterized template — label is short or duplicated.',
  },
  'axis-ancestor': {
    best: 'Relative xpath axis — depends on anchor stability.',
    good: 'Relative xpath axis — depends on anchor stability.',
    ok: 'Relative xpath axis — depends on anchor stability.',
    fragile: 'Relative xpath axis — anchor is unreliable.',
  },
  'axis-following': {
    best: 'Relative xpath axis — depends on document order stability.',
    good: 'Relative xpath axis — depends on document order stability.',
    ok: 'Relative xpath axis — depends on document order stability.',
    fragile: 'Relative xpath axis — order shifts will break this.',
  },
  'axis-preceding': {
    best: 'Relative xpath axis — depends on document order stability.',
    good: 'Relative xpath axis — depends on document order stability.',
    ok: 'Relative xpath axis — depends on document order stability.',
    fragile: 'Relative xpath axis — order shifts will break this.',
  },
  'axis-followingSibling': {
    best: 'Relative xpath axis — depends on sibling layout.',
    good: 'Relative xpath axis — depends on sibling layout.',
    ok: 'Relative xpath axis — depends on sibling layout.',
    fragile: 'Relative xpath axis — sibling reorder will break this.',
  },
  'axis-precedingSibling': {
    best: 'Relative xpath axis — depends on sibling layout.',
    good: 'Relative xpath axis — depends on sibling layout.',
    ok: 'Relative xpath axis — depends on sibling layout.',
    fragile: 'Relative xpath axis — sibling reorder will break this.',
  },
  'axis-parent': {
    best: 'Relative xpath axis — depends on direct parent.',
    good: 'Relative xpath axis — depends on direct parent.',
    ok: 'Relative xpath axis — depends on direct parent.',
    fragile: 'Relative xpath axis — parent wrapping changed.',
  },
  'rel-above': {
    best: 'Spatial proximity — depends on layout stability.',
    good: 'Spatial proximity — depends on layout stability.',
    ok: 'Spatial proximity — depends on layout stability.',
    fragile: 'Spatial proximity — layout shifts will break this.',
  },
  'rel-below': {
    best: 'Spatial proximity — depends on layout stability.',
    good: 'Spatial proximity — depends on layout stability.',
    ok: 'Spatial proximity — depends on layout stability.',
    fragile: 'Spatial proximity — layout shifts will break this.',
  },
  'rel-near': {
    best: 'Spatial proximity — depends on layout stability.',
    good: 'Spatial proximity — depends on layout stability.',
    ok: 'Spatial proximity — depends on layout stability.',
    fragile: 'Spatial proximity — layout shifts will break this.',
  },
  'rel-toLeftOf': {
    best: 'Spatial proximity — depends on layout stability.',
    good: 'Spatial proximity — depends on layout stability.',
    ok: 'Spatial proximity — depends on layout stability.',
    fragile: 'Spatial proximity — layout shifts will break this.',
  },
  'rel-toRightOf': {
    best: 'Spatial proximity — depends on layout stability.',
    good: 'Spatial proximity — depends on layout stability.',
    ok: 'Spatial proximity — depends on layout stability.',
    fragile: 'Spatial proximity — layout shifts will break this.',
  },
};

export function getRationale(c: Candidate): string {
  if (c.lints && c.lints.length) {
    const warn = c.lints.find((l) => l.severity === 'warn');
    if (warn) return warn.message;
    return c.lints[0].message;
  }
  // Candidate.kind is typed narrowly but rel-* kinds appear here at runtime —
  // cast through AnyLocatorKind to look them up in the rationale table.
  const byKind = KIND_RATIONALE[c.kind as AnyLocatorKind];
  if (byKind && byKind[c.stability]) return byKind[c.stability]!;
  return RATIONALE[c.stability];
}
